export const root: string;
export const read: string;
export const item: string;
export const title: string;
export const value: string;
export const arrival: string;
export const expense: string;
export const eventType: string;
export const trash: string;
